Разметка страницы
htmlacademy-htmlcss/2250277-sedona-36 pull request #2
Opened 2023-01-25 12:52 UTC by AlexPC19993

2023-01-25 16:07 UTC, DKukushkin91 requested changes

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +      <a class="navigation-link" href="https://htmlacademy.ru">.html academy</a>
ссылка ведёт на внешний ресурс добавь атрибут [target](https://developer.mozilla.org/ru/docs/Web/HTML/Element/a#attr-target)

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +          <li class="footer-social-item">
тэги поехали

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +            <a class="button" href="#">Telegram</a>
не забудь добавить aria-label с описанием ресурсов

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +      <div class="footer-social">
див вообще не нужен, если используем список

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +          <input type="submit" value="Подписаться">
input type=submit не используется, нужна button

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +          <p>Только полезная информация и никакого спама,<br>честное бойскаутское!</p>
Пока что тэг br вообще не используем, после стилей посмотрим.

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +            <a class="pagination-link" href="#">...</a>
span

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +            <a class="pagination-link pagination-current">1</a>
текущую тоже лучше отображать как span элемент

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +        <ul class="pagination">
лучше разместить всё в тэг [ol](https://developer.mozilla.org/ru/docs/Web/HTML/Element/ol)

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +                <a class="hotel-button hotel-button-blue" href="#">Подробнее</a>
Разве по смыслу больше связаны Гостиница и подробнее, что их нужно в 1 див расположить? Подумай еще, заходим в тупик, пишем мне

Это касается всех карточек.

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +                <a class="caption" href="#">Amara Resort & SPA</a>
это не ссылка, и не h3 это просто p

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +            <p class="photo">
Почему тэг [p](https://developer.mozilla.org/ru/docs/Web/HTML/Element/p)?

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +            <span class="visually-hidden">Показать карточки</span>
убирай спаны они не нужны

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +          <a href="#" class="button button-light">
1. Несколько ссылок с иконками, необходимо дополнительно обернуть в общего родителя (всегда старайся представить одинаковые элементы как элемент конструктора, соответственно им нужна какая-то опора, что бы эту детальку с несколькими элементами вставить  в любое место на сайте)
2. Это не ссылки, а кнопки

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +        <h2 class="visually-hidden">Гостиницы Седоны</h2>
Не нужен

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +       <section class="catalog">
1. отступ отличается от секции выше

2.  это всё 1 секция, фильтр в начале страницы относится к отображению списка.

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +            <button class="button" type="submit">Показать</button>
Кнопки убрать из fieldset и поместить в отдельный блок

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +                <button type="button" aria-label="Правый ползунок"></button>
aria-label="Стоимость до"

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +              <div class="bar"></div>
задумка не плохая, но это не див, а span

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +                <button type="button" aria-label="Левый ползунок"></button>
aria-label="Стоимость от"

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +              <div class="range-toggle range-toggle-min">
Зачем div? Кнопку не нужно оборачивать дополнительно в данном месте

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +              <label class="min-price">от <input type="text" name="min-price" value="0"></label>
тут нет label, пока подсказывать не буду, подумай как удачно можно будет это разместить, зайдешь в тупик пиши обсудим)

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +        <div>
div не нужен

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +                <input class="control-input" type="radio" name="product-group" value="hotel" checked>
product-group не удачное название для группы, лучше назвать room-type-group

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +        <div>
не нужен див

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +                  Бассейн
При использовании инпутов внутри лэйблов, всегда текст оборачиваем в <span> и ставим после input

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +        <div>
див не нужен, есть fieldset

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +
Лишний отступ, и отсюда начинается контент [формы ](https://developer.mozilla.org/ru/docs/Web/HTML/Element/form)

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +            <a class="breadcrumbs-item">Гостиницы</a>
это лучше объявить как span, т.к нужно избежать любых действий со стороны клиента, а так же это рекомендации по хлебным крошкам от [гугла](https://developers.google.com/search/docs/appearance/structured-data/breadcrumb?hl=ru#html).

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +            <a class="breadcrumbs-link" href="index.html">Главная</a>
Нужен будет атрибут aria-label т.к это иконка без описания

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +        <h1 class="visually-hidden">Поиск гостинницы в Седоне</h1>
Не верное содержание заголовка, посмотри содержимое в макете и  visually-hidden тут не нужен

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +              </a>
съехал тэг

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +               Сердце
Если ты хотел оставить нотацию

1. Человеку и так виден рисунок сердца, а людям с ограниченными возможностями слово "сердце" не принесёт ничего полезного.
2. Если мы попали в ситуацию, когда интерактивный элемент не содержит описания, но при этом мы хотим что бы люди использующие скринридер могли понять что делает этот элемент, необходимо добавить атрибут  **aria-label** для ссылки / кнопки и др. интерактивных элементов с описанием того, что это в контексте сайта.
**Пример:** aria-label='Избранное', aria-label='Поиск'

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +            </span>
Закрывающий тэг "уехал"

2023-01-25 16:07 UTC, DKukushkin91 commented on catalog.html
> +        <ul class="navigation-list navigation-user">
Это не список, а отдельный блок вне навигации

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +    <header class="main-header">
Всё тоже самое что и в файле Catalog

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +      <section class="description">
тут лучше всего поместить заголовок h1 скрытый классом visually-hidden

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +        <h1>Cедона - небольшой городок в аризоне,<br>заслуживающий большего!</h1>
1. заголовок с описанием должны быть в следующей секции
2. это тэг h2

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +        <h2 class="visually-hidden">Преимущества Седона</h2>
не нужен

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +            <h3 class="reason-item">Настоящий<br>городок</h3>
1.` <br>` не нужен
2. это` <p>`

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +            <span>—</span>
полоску сделаем в css, тире не нужно, оставь просто spanы

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +            <p class="reasons-description">Седона - не атракцион для<br>туристов, там течет своя жизнь</p>
нужно объединить текстовый контент

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +            <h3 class="reasone-item">Небольшая<br>площадь</h3>
Касается всех подобных карточек. Тэга h3 нет это p

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +            <span>—</span>
Касается всех подобных карточек. Полоску сделаем в css, тире не нужно, оставь просто spanы

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +            <p class="reasons-description">Все достопремичательности<br>находятся очень близко</p>
Касается всех подобных карточек. br убрать

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +            <div class="feature-item feature-item-house">
Касается всех подобных карточек. div не нужен

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +              <h4 class="title-item title-item-black">Жилье</h4>
Касается всех подобных карточек. Это тэг p

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +              <p>Рекомендуем пожить<br>в настоящем мотеле,<br>все как в кино!</p>
Касается всех подобных карточек. br убираем

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +      <section class="subscribe">
картинку нужно добавить в секцию

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +          <input type="submit" value="Подписаться">
это button

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +          <p>Только полезная информация и никакого спама,<br>честное бойскаутское!</p>
br убрать нужно

2023-01-25 16:07 UTC, DKukushkin91 commented on index.html
> +    <footer class="main-footer">
См. комментарии к catalog.html

2023-01-26 15:39 UTC, AlexPC19993 commented on catalog.html
> +                  Бассейн
Как обернуть текст?

2023-01-26 18:09 UTC, DKukushkin91 requested changes

2023-01-26 18:09 UTC, DKukushkin91 commented on catalog.html
>                <span class="visual-hiden">
Убрать пустые тэги

2023-01-26 18:09 UTC, DKukushkin91 commented on catalog.html
> +              <span class="visual-hiden">
Убрать пустой тэг

2023-01-26 18:09 UTC, DKukushkin91 commented on catalog.html
> +        <form>
Добавить атрибуты для проверки отправки формы

2023-01-26 18:09 UTC, DKukushkin91 commented on catalog.html
> +          <div>
див не нужен

2023-01-26 18:09 UTC, DKukushkin91 commented on catalog.html
> +                    Гостиница
нужно обернуть в span текст

2023-01-26 18:09 UTC, DKukushkin91 commented on catalog.html
> +          <button>Значки</button>
текст внутри тэгов не нужен, я говорил о aria-label

2023-01-26 18:09 UTC, DKukushkin91 commented on catalog.html
> +                <a class="hotel-button hotel-button-blue" href="#">Подробнее</a>
Чет так и не написал, но разметку не исправил, нужно подумать и исправить....подумай как ты читаешь эту карточку, посмотри на макет

2023-01-26 18:09 UTC, DKukushkin91 commented on catalog.html
> +              <p>Villas at Poco Diablo</p>
Тут я поторопился, единственный раз надеюсь простишь) Нужно поменять тэги P в названиях карточке на h3

2023-01-26 18:09 UTC, DKukushkin91 commented on catalog.html
> +        <ol class="pagination">
в span обычно завернута только активная страница и точки (нужно посмотреть макет), остальное должно быть ссылками

2023-01-26 18:09 UTC, DKukushkin91 commented on catalog.html
> +          <a class="button" href="#" aria-label="Vk">Vk</a>
ариа атрибут есть, текст внутри тэгов не нужен

2023-01-26 18:09 UTC, DKukushkin91 commented on index.html
>                <span class="visual-hiden">
пустые тэги нужно убрать

2023-01-26 18:09 UTC, DKukushkin91 commented on index.html
> +            <p class="reason-item">Настоящий городок</p>
тут так же как и в карточках товара, возвращаем тэг h3, с меня печенье, был видимо под воздействием полной луны

2023-01-26 18:09 UTC, DKukushkin91 commented on index.html
> +            Седоне</p>
странный перенос, нужно убрать

2023-01-26 18:09 UTC, DKukushkin91 commented on index.html
>          <form>
все формы должны быть с сылками и отправляться

2023-01-26 18:09 UTC, DKukushkin91 commented on index.html
> +        academy</a>
странные переносы) лучше максимально возможно писать в 1 строку

2023-01-26 18:09 UTC, DKukushkin91 commented on index.html
> +            <a class="button" href="#" aria-label="Youtube">Youtube</a>
убрать текстовое описание из тэгов, т.к есть ариа атрибут

2023-01-27 08:42 UTC, AlexPC19993 commented on catalog.html
>                <span class="visual-hiden">
corrected

2023-01-27 08:42 UTC, AlexPC19993 commented on catalog.html
> +              <span class="visual-hiden">
corrected

2023-01-27 08:42 UTC, AlexPC19993 commented on catalog.html
> +        <form>
corrected

2023-01-27 08:42 UTC, AlexPC19993 commented on catalog.html
> +          <div>
corrected

2023-01-27 08:43 UTC, AlexPC19993 commented on catalog.html
> +                    Гостиница
corrected

2023-01-27 08:56 UTC, AlexPC19993 commented on catalog.html
> +          <button>Значки</button>
corrected

2023-01-27 08:59 UTC, AlexPC19993 commented on catalog.html
> +              <p>Villas at Poco Diablo</p>
corrected

2023-01-27 09:01 UTC, AlexPC19993 commented on catalog.html
> +          <a class="button" href="#" aria-label="Vk">Vk</a>
corrected

2023-01-27 09:02 UTC, AlexPC19993 commented on index.html
>                <span class="visual-hiden">
corrected

2023-01-27 09:03 UTC, AlexPC19993 commented on index.html
> +            <p class="reason-item">Настоящий городок</p>
corrected

2023-01-27 09:10 UTC, AlexPC19993 commented on index.html
> +            <a class="button" href="#" aria-label="Youtube">Youtube</a>
corrected

2023-01-27 09:35 UTC, AlexPC19993 commented on index.html
>          <form>
corrected

2023-01-27 10:24 UTC, AlexPC19993 commented on index.html
> +            Седоне</p>
corrected

2023-01-27 10:24 UTC, AlexPC19993 commented on index.html
> +        academy</a>
corrected

2023-01-27 14:16 UTC, merged