Сетки на Флексах и Гридах
htmlacademy-htmlcss/2250277-sedona-36 pull request #6
Opened 2023-03-01 16:47 UTC by AlexPC19993

2023-03-01 20:40 UTC, DKukushkin91 requested changes

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
>                    </svg>
1. Опечатка в теге `a` на 61 строке. Атрибут называется aria-label.
2. Необходимо выровнять breadcrumbs с помощью align-items: center;

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
> -                <span>Гостиницы</span>
span уместнее, это всё такие не параграф совсем.

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
> +              <li>
Стрелка не элемент списка. И её вообще необходимо убрать из разметки.
Нужно использовать псевдо классы  `:not, :last-child, ::after` для вставки через контент изображения стрелки

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
> +                <div class="actions-container">
див нужно убрать

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
> +                  <svg width="140" height="37" viewBox="0 0 140 37" fill="none" xmlns="http://www.w3.org/2000/svg">
С звёздами никакого взаимодействия не будет, тут не нужен инлайн свг. Положи их в img

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
> +                <p class="price">От 5000 Р.</p>
![изображение](https://user-images.githubusercontent.com/62586082/222218565-8770b38d-39f8-4ee5-a403-74905b4aab97.png)
На макете совсем иначе указаны ценники. Исправь.

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
> +            <div class="pagination-container">
какой смысл в контейнере. Нужно убрать и необходимые стили перенести на список

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
> +                  <a class="active" href="#">1</a>
конкретно текущая страница это span, тем самым мы обезопасим себя от лишних обновлений страницы

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
> +            <a class="social-link" href="#" aria-label="Vk"><svg width="25" height="15" viewBox="0 0 25 15" fill="none"
Форматируй код. 
Неправильно:
Невозможно ориентироваться в коде. Не ясна вложенность элементов.
![изображение](https://user-images.githubusercontent.com/62586082/222219862-0a78836a-6453-4a85-ab90-3970d79fbe5a.png)

Правильно:
Элементы идут друг за другом, вложенность четко просматривается.
![изображение](https://user-images.githubusercontent.com/62586082/222219951-6385d550-519d-41f6-b9ea-2d429130766c.png)

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  padding: 0 70px;
нужно задать 

    column-gap: 30px;
    justify-content: space-between;

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  padding-left: 30px;
`padding-left` нужно убрать

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  align-items: center;
последнему ребенку нужно задать margin-left: 20px

    .navigation-item:last-child {
        margin-left: 20px
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>    line-height: 24px;
необходимо задать напрямую` font-family: "PT Sans", sans-serif`; т.к есть кнопка в этом классе, кнопки не наследуют` font-family`. ЛИБО нужно всем кнопкам дать класс `.button` и определить для него шрифт `font-family: inherit`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  padding: 20px 0;
заменить `display: block, padding: 20px 0;`

на:

    display: flex;
    flex-direction: column;
    height: 100%;
    justify-content: center;
    position: relative;

2023-03-01 20:40 UTC, DKukushkin91 commented on index.html
>                  <li class="features-item">
57 строка <div class="page-container"> нужно убрать, нет стилей, не несет никакой логики и ценности для проекта

59 строка. Убрать обёртку <div class='images'> нет смысла

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>  }
1. class images удаляем. 


2. классу description заменить все стили на: 


          .description {
              background-image: url(../images/index-background.jpg);
              background-size: cover;
              background-repeat: no-repeat;
              background-color: blue;
              min-height: 485px;
              padding: 51px 0 57px 0;
              text-align: center;
          }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  padding: 69px 275.5px;
Изменить стили на:

    .reason-criteria {
        text-align: center;
        width: 100%;
        max-width: 651px;
        margin: 0 auto;
        padding: 69px 0;
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
.reason-item:first-child,
      .reason-item:last-child {
            background-color: #82B3D3;
            color: #FFFFFF;
            display: flex;
          }
      }

вместо этого добавить 1 и последнему reason-item класс full-width

и этому классу задать 

    .full-width {
        background-color: #82B3D3;
        color: #FFFFFF;
        display: flex;
        padding: 0;
        justify-content: space-between;
        align-items: unset;
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>  img {
изменить свойство object-fit в img
на `object-fit: cover;`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
Затем прописать стили для контейнера в нём .

      .full-width .reason-item-container {
          align-self: center;
          margin: 0 auto;
          padding: 102px 0;
      }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
классу .reason-item добавляем стили

    .reason-item {
        flex: 1 1 auto;
        min-height: 385px;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 102px 0;
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  right: 256px;
Это обсуждали на созвоне.
актуализируй позицию.

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>  .reason-title {
1. `.reason-title` и `.reason-description` не должны иметь padding. 
2.  `.reason-title` добавить `margin-bottom: 30px;`
3. `.reason-description-wite` переименовать в `.reason-description-white` т.к ошибка в слове
4.  `.reason-description-white`  убрать все свойства, добавить `color: #ffffff`. В разметке добавить элементу с классом   `.reason-description-white`  класс  `.reason-description`
5. в css файле   `.reason-description-white`  должен идти **под**   `.reason-description` не забываем о каскаде, это даёт нам переопределять стили

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  padding: 64px 348px;
Изменить стили на 

    .offer {
        text-align: center;
        width: 100%;
        max-width: 505px;
        margin: 0 auto;
        padding: 64px 0;
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  margin-top: 20px;
зачем тут `margin-top`?  У нас у заголовка есть отступ вниз. `margin-top` нужно убрать

2023-03-01 20:40 UTC, DKukushkin91 commented on index.html
>                  <li class="features-item">
в features-item 
поместить div а в него весь контент

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>    padding: 81px 85px;
измени на `padding: 81px 0;`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>    padding: 81px 85px;
выше писал о внутренней обертке в `features-item`

назови её `features-item-container`

далее стили для неё 
    
    .features-item-container {
        width: 100%;
        max-width: 230px;
        display: flex;
        flex-direction: column;
        row-gap: 30px;
    }

так же не забудь убрать у дочерних `p` и `h` тегов отступы

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
классу ` .reason-item-container ` полностью меняем стили 

    .reason-item-container {
        width: 100%;
        max-width: 230px;
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>  /*search*/
`.search-item ` изменить `width` на `width: 100%;` и после добавить `max-width: 592px;`

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
>              <ul class="hotels">
это не hotels, нужно поменять на hotels-list

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
>            <section>
добавляем класс hotels

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>    padding: 50px 70px 40px;
`padding` убираем 
добавляем `margin-bottom: 40px; `

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>  .hotels {
переименовываем в `hotels-list`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
на тег section определяем класс hotels

стили 

    .hotels {
        padding: 50px 70px 60px;
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  padding: 0 70px 40px;
меняем на `padding: 0;`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>    margin: 0;
меняем на `margin: 0 0 40px 0;`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  grid-column: 1/3;
не понял причины почему решил сделать не так как на созвоне, а понадобится нам разделить карточку на 5 колонок, будем искать картинку и задавать ей grid-column: 1/6? 

меняем на `grid-column: 1/-1;`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>    padding: 20px;
меняем на `padding: 20px 19px;`

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
> +                <div class="actions-container">
обертку убрать. Класс от неё повесить на `label`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  height: 48px;
так же нужно не забыть и обнулять у всех `button` `padding` он идёт с 'завода'

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +.fake::before {
не стоит того что бы использовать content и вставлять описание через css. Порождает много зависимостей и слишком неявно, для других разработчиков, что будут смотреть после тебя разметку например. 

Как и писал в телеге. Просто задай смену фона, цвет текста и т.п, а сам текст пусть будет в разметке указан, менять его не нужно по клику (это делается на js)

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +.input-ceckbox:checked + .fake::before{
`.fake` нужно переименовать в `input-checkbox-text` и внести в разметке в него текст с макета

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  padding: 40px 70px 60px;
изменить стили на

    .pagination-container {
        padding-top: 40px;
        border-top: 1px solid #E6E6E6;
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  margin: 0;
добавить `width: 100%` и `max-width: 400px;`, `column-gap: 8px;`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +.pagination-item:not(:last-child) {
убрать вообще

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>  .active {
изменяется только `background-color`; его нужно оставить остальное убрать. Просто добавь в самом `html` класс `pagination-link` к классу `active`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>    display: flex;
изменить стили на 

    .pagination-item {
        width: 60px;
        height: 60px;
        background-color: #82B3D3;
        border-radius: 4px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
> +  padding: 12px 24px;
изменить стили на 

    .pagination-link {
        font-weight: 700;
        font-size: 20px;
        line-height: 36px;
        text-align: center;
        text-decoration: none;
        color: #FFFFFF;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 100%;
        height: 100%;
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>    line-height: 36px;
`.subscribe-item` изменить `width` на `width: 100%` и `max-width: 684px`

2023-03-01 20:40 UTC, DKukushkin91 commented on catalog.html
>            <section class="subscribe-catalog">
тут не нужно выдумывать новых секций, у нас уже есть все стили с главной страницы и разметка тоже.
Это то на что нужно заменить.
      
      <section class="subscribe subscribe-catalog">
          <div class="subscribe-item">
              <h2>Подпишитесь на рассылку</h2>
              <p>Только полезная информация и никакого спама,<br>честное бойскаутское!</p>
              <form action="#">
                  <input name="email" type="email" placeholder="Ваш E-mail" required="">
                  <button class="button" type="submit">Подписаться</button>
              </form>
          </div>
      </section>

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>  .subscribe-catalog {
Заменить стили на 

    .subscribe-catalog {
        background: 0;
        color: #000;
    }

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
>  .subscribe-catalog {
Переместить сам класс сразу под `.subscribe` в `css`

2023-03-01 20:40 UTC, DKukushkin91 commented on styles/styles.css
удалить из стилей правила
1. `.subscribe-catalog-item`,
2.  `.subscribe-catalog h2`,
3.  `.subscribe-catalog p`, 
4. `.subscribe-catalog input`,
5. `.subscribe-catalog button`
6. `.subscribe-catalog-item form`

2023-03-02 08:47 UTC, AlexPC19993 commented on catalog.html
>                    </svg>
corrected

2023-03-02 08:48 UTC, AlexPC19993 commented on catalog.html
> -                <span>Гостиницы</span>
corrected

2023-03-02 09:01 UTC, AlexPC19993 commented on catalog.html
> +                <div class="actions-container">
corrected

2023-03-02 09:01 UTC, AlexPC19993 commented on catalog.html
> +                <div class="actions-container">
corrected

2023-03-02 10:20 UTC, AlexPC19993 commented on catalog.html
> +                <p class="price">От 5000 Р.</p>
corrected

2023-03-02 10:20 UTC, AlexPC19993 commented on catalog.html
> +                  <svg width="140" height="37" viewBox="0 0 140 37" fill="none" xmlns="http://www.w3.org/2000/svg">
corrected

2023-03-02 10:34 UTC, AlexPC19993 commented on catalog.html
> +            <a class="social-link" href="#" aria-label="Vk"><svg width="25" height="15" viewBox="0 0 25 15" fill="none"
corrected

2023-03-02 10:39 UTC, AlexPC19993 commented on catalog.html
> +            <div class="pagination-container">
corrected

2023-03-02 10:40 UTC, AlexPC19993 commented on catalog.html
> +                  <a class="active" href="#">1</a>
corrected

2023-03-02 10:43 UTC, AlexPC19993 commented on styles/styles.css
> +  padding: 0 70px;
corrected

2023-03-02 10:43 UTC, AlexPC19993 commented on styles/styles.css
> +  padding-left: 30px;
corrected

2023-03-02 10:46 UTC, AlexPC19993 commented on styles/styles.css
> +  align-items: center;
corrected

2023-03-02 11:27 UTC, AlexPC19993 commented on styles/styles.css
>    line-height: 24px;
corrected

2023-03-02 13:24 UTC, AlexPC19993 commented on styles/styles.css
> +  padding: 20px 0;
corrected

2023-03-02 13:35 UTC, AlexPC19993 commented on styles/styles.css
>  }
corrected

2023-03-02 13:37 UTC, AlexPC19993 commented on styles/styles.css
> +  padding: 69px 275.5px;
corrected

2023-03-02 13:57 UTC, AlexPC19993 commented on styles/styles.css
>  img {
corrected

2023-03-02 14:07 UTC, AlexPC19993 commented on styles/styles.css
corrected

2023-03-02 14:09 UTC, AlexPC19993 commented on styles/styles.css
>  .reason-title {
corrected

2023-03-02 14:21 UTC, AlexPC19993 commented on index.html
>                  <li class="features-item">
corrected

2023-03-02 14:23 UTC, AlexPC19993 commented on styles/styles.css
> +  padding: 64px 348px;
corrected

2023-03-02 14:25 UTC, AlexPC19993 commented on styles/styles.css
> +  margin-top: 20px;
corrected

2023-03-02 14:39 UTC, AlexPC19993 commented on styles/styles.css
>    padding: 81px 85px;
corrected

2023-03-02 14:40 UTC, AlexPC19993 commented on styles/styles.css
>  /*search*/
corrected

2023-03-02 14:44 UTC, AlexPC19993 commented on catalog.html
>              <ul class="hotels">
corrected

2023-03-02 14:45 UTC, AlexPC19993 commented on catalog.html
>            <section>
corrected

2023-03-02 14:48 UTC, AlexPC19993 commented on styles/styles.css
>  .hotels {
corrected

2023-03-02 14:48 UTC, AlexPC19993 commented on styles/styles.css
>    padding: 50px 70px 40px;
corrected

2023-03-02 14:51 UTC, AlexPC19993 commented on styles/styles.css
> +  padding: 0 70px 40px;
corrected

2023-03-02 14:53 UTC, AlexPC19993 commented on styles/styles.css
>    margin: 0;
corrected

2023-03-02 14:54 UTC, AlexPC19993 commented on styles/styles.css
> +  grid-column: 1/3;
corrected

2023-03-02 14:56 UTC, AlexPC19993 commented on styles/styles.css
>    padding: 20px;
corrected

2023-03-02 15:42 UTC, AlexPC19993 commented on styles/styles.css
> +  padding: 40px 70px 60px;
corrected

2023-03-02 16:01 UTC, AlexPC19993 commented on styles/styles.css
> +  margin: 0;
corrected

2023-03-02 16:02 UTC, AlexPC19993 commented on styles/styles.css
> +.pagination-item:not(:last-child) {
corrected

2023-03-02 16:02 UTC, AlexPC19993 commented on styles/styles.css
>  .active {
corrected

2023-03-02 16:03 UTC, AlexPC19993 commented on styles/styles.css
> +  padding: 12px 24px;
corrected

2023-03-02 16:06 UTC, AlexPC19993 commented on styles/styles.css
>    line-height: 36px;
corrected

2023-03-02 16:29 UTC, AlexPC19993 commented on catalog.html
>            <section class="subscribe-catalog">
corrected

2023-03-02 16:29 UTC, AlexPC19993 commented on styles/styles.css
>  .subscribe-catalog {
corrected

2023-03-02 16:29 UTC, AlexPC19993 commented on styles/styles.css
corrected

2023-03-02 17:30 UTC, AlexPC19993 commented on styles/styles.css
> +  right: 256px;
corrected

2023-03-02 17:31 UTC, AlexPC19993 commented on styles/styles.css
corrected

2023-03-06 11:42 UTC, AlexPC19993 commented on styles/styles.css
>    display: flex;
corrected

2023-03-06 17:31 UTC, merged